version: '3.8'

services:
  # Основная база данных для всей экосистемы
  postgres:
    image: postgres:16-alpine
    container_name: void-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: void_password
      POSTGRES_DB: void_db
    networks:
      - void-secure-backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Сюда мы положим скрипт инициализации таблиц
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d void_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Кэш и очереди для SSO
  redis:
    image: redis:7-alpine
    container_name: void-redis
    restart: always
    networks:
      - void-secure-backend

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: void-auth-service
    command: npm start -w @void/auth-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=void_password
      - DB_NAME=void_db
      - REDIS_HOST=redis
      - JWT_SECRET=super_secret_key
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - void-secure-backend
      - void-public-edge


  payment-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: void-payment-gateway
    command: npm start -w @void/payment-gateway
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=void_password
      - DB_NAME=void_db
      - REDIS_HOST=redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - void-secure-backend
      - void-public-edge

  marketplace-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: void-marketplace-service
    command: npm start -w @void/marketplace-service
    ports:
      - "3002:3002" # Выставляем API маркетплейса для Next.js фронтенда
    environment:
      - PORT=3002
      - DB_HOST=postgres
      - DB_PORT=5432 # Нативный внутренний порт Postgres в защищенной сети
      - DB_USER=postgres
      - DB_PASSWORD=void_password
      - DB_NAME=void_db
      - REDIS_HOST=redis
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - void-secure-backend
      - void-public-edge


  # Аналитическая колоночная СУБД для финтех-логов Саги
  clickhouse:
    image: clickhouse/clickhouse-server:24.8-alpine
    container_name: void-clickhouse
    restart: always
    environment:
      - CLICKHOUSE_USER=void_analytics
      - CLICKHOUSE_PASSWORD=analytics_password
      - CLICKHOUSE_DB=void_analytics_db
    networks:
      - void-secure-backend
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      # 🟢 Пробрасываем скрипт инициализации аналитических таблиц
      - ./infra/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  analytics-logs-collector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: void-analytics-logs-collector
    command: npm start -w @void/analytics-logs-collector
    environment:
      - REDIS_HOST=redis
      - CLICKHOUSE_HOST=http://clickhouse:8123
      - CLICKHOUSE_USER=void_analytics
      - CLICKHOUSE_PASSWORD=analytics_password
      - CLICKHOUSE_DB=void_analytics_db
    depends_on:
      redis:
        condition: service_started
      clickhouse:
        condition: service_healthy # 🟢 Ждем, пока ClickHouse пройдет внутренний healthcheck и развернет наши таблицы!
    networks:
      - void-secure-backend
      - void-public-edge

volumes:
  postgres_data:
  clickhouse_data:

networks:
  void-secure-backend:
    driver: bridge
  void-public-edge:
    driver: bridge
